// ═══════════════════════════════════════════
//  PiDEX i18n — LANG 변경 시 setLang() 호출
//  ko|en|id|zh|ja|es|vi|hi|pt|tl|fr
// ═══════════════════════════════════════════

const STRINGS = {
  // ── App / login ──
  processing:       { ko:'처리 중...',                  en:'Processing...',                id:'Memproses...',         zh:'处理中...',          ja:'処理中...',               es:'Procesando...',             vi:'Đang xử lý...',          hi:'प्रसंस्करण...',   pt:'Processando...',         tl:'Pinoproseso...',           fr:'Traitement...' },
  connecting:       { ko:'Pi 지갑 연결 중...',           en:'Connecting Pi Wallet...',     id:'Menghubungkan Dompet Pi...', zh:'连接 Pi 钱包中...', ja:'Piウォレット接続中...',  es:'Conectando Pi Wallet...',  vi:'Đang kết nối Pi Wallet...', hi:'Pi वॉलेट जोड़ रहे हैं...', pt:'Conectando Pi Wallet...', tl:'Kumokonekta sa Pi Wallet...', fr:'Connexion Pi Wallet...' },
  login_fail:       { ko:'로그인 실패. Pi Browser에서 실행해주세요.', en:'Login failed. Please run in Pi Browser.', id:'Login gagal. Jalankan di Pi Browser.', zh:'登录失败，请在 Pi Browser 中运行。', ja:'ログイン失敗。Pi Browserで実行してください。', es:'Error de inicio de sesión. Ejecute en Pi Browser.', vi:'Đăng nhập thất bại. Hãy chạy trong Pi Browser.', hi:'लॉगिन विफल। Pi Browser में चलाएं।', pt:'Falha no login. Execute no Pi Browser.', tl:'Nabigo ang login. Patakbuhin sa Pi Browser.', fr:'Échec de connexion. Lancez dans Pi Browser.' },
  loading_pidex:    { ko:'PiDEX 데이터 로드 중...',      en:'Loading PiDEX data...',       id:'Memuat data PiDEX...',  zh:'加载 PiDEX 数据中...',  ja:'PiDEXデータ読込中...',    es:'Cargando datos de PiDEX...',vi:'Đang tải dữ liệu PiDEX...', hi:'PiDEX डेटा लोड हो रहा है...', pt:'Carregando dados PiDEX...', tl:'Nilo-load ang datos ng PiDEX...', fr:'Chargement des données PiDEX...' },
  sub_active:       { ko:'구독중',                       en:'Active',                      id:'Aktif',                 zh:'订阅中',             ja:'サブスク中',              es:'Activo',                   vi:'Đang đăng ký',           hi:'सक्रिय',          pt:'Ativo',                  tl:'Aktibo',                   fr:'Actif' },

  // ── Nav ──
  nav_dex:          { ko:'덱스',   en:'DEX',       id:'DEX',       zh:'交易所', ja:'DEX',         es:'DEX',      vi:'DEX',      hi:'DEX',         pt:'DEX',       tl:'DEX',       fr:'DEX' },
  nav_lp:           { ko:'LP 계산', en:'LP Calc',  id:'Kalk. LP',  zh:'LP 计算', ja:'LP計算',      es:'LP Calc',  vi:'Tính LP',  hi:'LP गणना',    pt:'LP Calc',   tl:'LP Calc',   fr:'LP Calc' },
  nav_arb:          { ko:'차익 탐색', en:'Arb Finder', id:'Arb Finder', zh:'套利查找', ja:'アービトラージ', es:'Arb Finder', vi:'Tìm Arb', hi:'आर्बिट्राज', pt:'Arb Finder', tl:'Arb Finder', fr:'Arb Finder' },
  nav_swap:         { ko:'스왑',   en:'Swap',      id:'Swap',      zh:'兑换',   ja:'スワップ',    es:'Swap',     vi:'Swap',     hi:'स्वैप',      pt:'Swap',      tl:'Swap',      fr:'Swap' },
  nav_wallet:       { ko:'지갑',   en:'Wallet',    id:'Dompet',    zh:'钱包',   ja:'ウォレット',  es:'Cartera',  vi:'Ví',       hi:'वॉलेट',      pt:'Carteira',  tl:'Wallet',    fr:'Portefeuille' },
  nav_info:         { ko:'정보',   en:'Info',      id:'Info',      zh:'信息',   ja:'情報',        es:'Info',     vi:'Thông tin', hi:'जानकारी',   pt:'Info',      tl:'Info',      fr:'Info' },
  btn_info:         { ko:'정보',   en:'Info',      id:'Info',      zh:'信息',   ja:'情報',        es:'Info',     vi:'Thông tin', hi:'जानकारी',   pt:'Info',      tl:'Info',      fr:'Info' },
  btn_utils:        { ko:'유틸 모음', en:'My Apps', id:'Aplikasi', zh:'工具合集', ja:'アプリ一覧', es:'Mis Apps', vi:'Ứng dụng', hi:'मेरे ऐप्स', pt:'Meus Apps', tl:'Mga App',  fr:'Mes Apps' },
  utils_title:      { ko:'유틸 모음', en:'My Utilities', id:'Utilitas Saya', zh:'我的工具集', ja:'マイユーティリティ', es:'Mis Utilidades', vi:'Tiện ích của tôi', hi:'मेरे उपकरण', pt:'Minhas Utilidades', tl:'Aking Mga Utility', fr:'Mes Utilitaires' },
  utils_soon:       { ko:'유틸 목록이 곧 추가됩니다 :)', en:'More utilities coming soon :)', id:'Utilitas lainnya segera hadir :)', zh:'更多工具即将推出 :)', ja:'他のユーティリティが近日公開 :)', es:'Más utilidades próximamente :)', vi:'Thêm tiện ích sắp ra mắt :)', hi:'और उपकरण जल्द आ रहे हैं :)', pt:'Mais utilitários em breve :)', tl:'Mas maraming utility ang darating :)', fr:"Plus d'utilitaires bientôt :)" },
  btn_close:        { ko:'닫기',   en:'Close',     id:'Tutup',     zh:'关闭',   ja:'閉じる',      es:'Cerrar',   vi:'Đóng',      hi:'बंद करें',  pt:'Fechar',    tl:'Isara',     fr:'Fermer' },

  // ── Pull to refresh ──
  ptr_pull:         { ko:'당겨서 새로고침', en:'Pull to refresh', id:'Tarik untuk refresh', zh:'下拉刷新', ja:'引いて更新', es:'Desliza para actualizar', vi:'Kéo xuống để làm mới', hi:'खींचकर ताज़ा करें', pt:'Puxe para atualizar', tl:'I-pull para i-refresh', fr:'Tirer pour actualiser' },

  // ── Dashboard ──
  dash_title:       { ko:'PiDEX 현황',       en:'Network Overview',      id:'Ringkasan Jaringan', zh:'PiDEX 概览',      ja:'PiDEX 概況',         es:'Resumen de la Red',          vi:'Tổng quan mạng lưới',      hi:'नेटवर्क अवलोकन',     pt:'Visão Geral da Rede',          tl:'Pangkalahatang-tanaw ng Network', fr:'Aperçu du Réseau' },
  dash_loading:     { ko:'풀 데이터 로드 중...', en:'Loading pool data...', id:'Memuat data pool...', zh:'加载池数据中...',  ja:'プールデータ読込中...', es:'Cargando datos del pool...', vi:'Đang tải dữ liệu pool...', hi:'पूल डेटा लोड हो रहा है...', pt:'Carregando dados do pool...', tl:'Nilo-load ang datos ng pool...', fr:'Chargement des données du pool...' },
  dash_network:     { ko:'네트워크', en:'Network',    id:'Jaringan',  zh:'网络',   ja:'ネットワーク', es:'Red',    vi:'Mạng',    hi:'नेटवर्क',   pt:'Rede',      tl:'Network',    fr:'Réseau' },
  dash_total_pools: { ko:'총 풀 수', en:'Total Pools', id:'Total Pool', zh:'总池数', ja:'総プール数', es:'Total de Pools', vi:'Tổng số pool', hi:'कुल पूल', pt:'Total de Pools', tl:'Kabuuang Pools', fr:'Total des Pools' },
  dash_pi_pairs:    { ko:'Pi 포함 풀', en:'Pi Pairs', id:'Pasangan Pi', zh:'含 Pi 池', ja:'Piを含むプール', es:'Pares con Pi', vi:'Các cặp Pi', hi:'Pi के साथ पूल', pt:'Pares com Pi', tl:'Mga Pares na may Pi', fr:'Paires avec Pi' },
  dash_tokens:      { ko:'고유 토큰', en:'Unique Tokens', id:'Token Unik', zh:'独特代币', ja:'ユニークトークン', es:'Tokens únicos', vi:'Token độc nhất', hi:'अनूठे टोकन', pt:'Tokens únicos', tl:'Natatanging mga Token', fr:'Tokens uniques' },
  dash_amm_fee:     { ko:'AMM 수수료', en:'Avg AMM Fee', id:'Biaya AMM Rata-rata', zh:'平均 AMM 手续费', ja:'平均AMM手数料', es:'Comisión AMM media', vi:'Phí AMM trung bình', hi:'औसत AMM शुल्क', pt:'Taxa AMM média', tl:'Avg AMM Fee', fr:'Frais AMM moyens' },
  dash_liquidity:   { ko:'유동성', en:'Liquidity', id:'Likuiditas', zh:'流动性', ja:'流動性', es:'Liquidez', vi:'Thanh khoản', hi:'तरलता', pt:'Liquidez', tl:'Liquidity', fr:'Liquidité' },
  dash_total_liq:   { ko:'전체 유동성 합산', en:'Total Liquidity', id:'Total Likuiditas', zh:'总流动性', ja:'総流動性', es:'Liquidez total', vi:'Tổng thanh khoản', hi:'कुल तरलता', pt:'Liquidez total', tl:'Kabuuang Liquidity', fr:'Liquidité totale' },
  dash_gas:         { ko:'권장 가스비', en:'Recommended Gas', id:'Gas Rekomendasi', zh:'推荐 Gas 费', ja:'推奨ガス代', es:'Gas recomendado', vi:'Gas đề xuất', hi:'अनुशंसित गैस', pt:'Gas recomendado', tl:'Inirerekomendang Gas', fr:'Gas recommandé' },
  dash_top_pools:   { ko:'유동성 상위 풀', en:'Top Pools by Liquidity', id:'Pool Teratas', zh:'流动性最高池', ja:'流動性上位プール', es:'Pools por liquidez', vi:'Pool hàng đầu theo thanh khoản', hi:'शीर्ष पूल (तरलता से)', pt:'Melhores pools por liquidez', tl:'Mga nangungunang Pool ayon sa Liquidity', fr:'Meilleurs pools par liquidité' },
  dash_updated:     { ko:'데이터 기준 시각', en:'Data as of', id:'Data per', zh:'数据基准时刻', ja:'データ基準時刻', es:'Datos a partir de', vi:'Dữ liệu tính đến', hi:'डेटा के अनुसार', pt:'Dados até', tl:'Data bilang ng', fr:'Données au' },
  dash_fail:        { ko:'데이터 로드 실패', en:'Data load failed', id:'Gagal memuat data', zh:'数据加载失败', ja:'データ読み込み失敗', es:'Error al cargar datos', vi:'Lỗi tải dữ liệu', hi:'डेटा लोड विफल', pt:'Falha ao carregar dados', tl:'Nabigo ang pag-load ng datos', fr:'Échec du chargement des données' },

  // ── LP Helper ──
  lp_title:         { ko:'LP 계산기',  en:'LP Calculator',         id:'Kalkulator LP',    zh:'LP 计算器',    ja:'LP計算機',          es:'Calculadora LP',          vi:'Máy tính LP',          hi:'LP कैलकुलेटर',   pt:'Calculadora LP',        tl:'LP Calculator',          fr:'Calculatrice LP' },
  lp_search_ph:     { ko:'코인 검색 (예: USDT)', en:'Search token (e.g. USDT)', id:'Cari token (mis: USDT)', zh:'搜索代币 (例如: USDT)', ja:'トークン検索（例: USDT）', es:'Buscar token (ej: USDT)', vi:'Tìm token (ví dụ: USDT)', hi:'टोकन खोजें (जैसे: USDT)', pt:'Buscar token (ex: USDT)', tl:'Hanapin ang token (hal: USDT)', fr:'Chercher token (ex: USDT)' },
  lp_sort_liq:      { ko:'유동성 높음', en:'Liquidity', id:'Likuiditas', zh:'流动性高', ja:'流動性高い', es:'Liquidez', vi:'Thanh khoản cao', hi:'उच्च तरलता', pt:'Liquidez', tl:'Liquidity', fr:'Liquidité' },
  lp_pi_only:       { ko:'파이포함만', en:'Pi Pairs', id:'Hanya Pi', zh:'仅含 Pi', ja:'Piのみ', es:'Solo Pi', vi:'Chỉ Pi', hi:'केवल Pi', pt:'Apenas Pi', tl:'Pi lang', fr:'Pi seulement' },
  lp_pi_first:      { ko:'파이우선', en:'Pi First', id:'Pi Dahulu', zh:'Pi 优先', ja:'Pi優先', es:'Pi primero', vi:'Pi trước', hi:'Pi पहले', pt:'Pi primeiro', tl:'Pi muna', fr:'Pi en premier' },
  lp_new_pool:      { ko:'새풀', en:'New Pool', id:'Pool Baru', zh:'新池', ja:'新しいプール', es:'Nuevo pool', vi:'Pool mới', hi:'नया पूल', pt:'Novo pool', tl:'Bagong Pool', fr:'Nouveau pool' },
  lp_loading:       { ko:'풀 목록 불러오는 중...', en:'Loading pools...', id:'Memuat daftar pool...', zh:'加载池列表中...', ja:'プールリスト読込中...', es:'Cargando pools...', vi:'Đang tải danh sách pool...', hi:'पूल सूची लोड हो रही है...', pt:'Carregando pools...', tl:'Nilo-load ang mga pool...', fr:'Chargement des pools...' },
  lp_load_fail:     { ko:'풀 목록 조회 실패', en:'Pool list failed', id:'Gagal memuat pool', zh:'池列表加载失败', ja:'プールリスト取得失敗', es:'Error al cargar pool', vi:'Lỗi tải danh sách pool', hi:'पूल सूची विफल', pt:'Falha ao carregar pool', tl:'Nabigo ang pag-load ng pool', fr:'Échec chargement pool' },
  lp_no_pools:      { ko:'조건에 맞는 풀 없음', en:'No matching pools', id:'Tidak ada pool yang cocok', zh:'无匹配池', ja:'条件に合うプールなし', es:'Sin pools que coincidan', vi:'Không có pool phù hợp', hi:'कोई मिलान पूल नहीं', pt:'Nenhum pool correspondente', tl:'Walang mga pool na nagtutugma', fr:'Aucun pool correspondant' },
  lp_new_title:     { ko:'아직 풀이 없는 토큰 조합', en:'Pairs without a pool', id:'Pasangan tanpa pool', zh:'尚无流动池的代币对', ja:'プールが存在しないトークン組合せ', es:'Pares sin pool existente', vi:'Các cặp chưa có pool', hi:'बिना पूल के टोकन जोड़े', pt:'Pares sem pool existente', tl:'Mga pares na walang pool', fr:'Paires sans pool existant' },
  lp_no_new:        { ko:'조건에 맞는 새풀 조합 없음', en:'No new pool pairs found', id:'Tidak ada pasangan pool baru', zh:'无匹配新池组合', ja:'条件に合う新プール組合せなし', es:'Sin nuevas combinaciones de pool', vi:'Không có cặp pool mới nào phù hợp', hi:'कोई नया पूल संयोजन नहीं', pt:'Nenhuma combinação de pool novo', tl:'Walang bagong pool pair na natagpuan', fr:'Aucune nouvelle combinaison de pool' },
  lp_no_pool_tag:   { ko:'풀 없음', en:'No pool', id:'Belum ada pool', zh:'无池', ja:'プールなし', es:'Sin pool', vi:'Chưa có pool', hi:'कोई पूल नहीं', pt:'Sem pool', tl:'Walang pool', fr:'Sans pool' },
  lp_selected:      { ko:'선택된 풀', en:'Selected Pool', id:'Pool Dipilih', zh:'已选择池', ja:'選択済みプール', es:'Pool seleccionado', vi:'Pool đã chọn', hi:'चुना गया पूल', pt:'Pool selecionado', tl:'Piniling Pool', fr:'Pool sélectionné' },
  lp_deposit_pi:    { ko:'투입할 총 Pi', en:'Total Pi to Deposit', id:'Total Pi untuk Deposit', zh:'存入的总 Pi', ja:'預入する総Pi', es:'Pi total a depositar', vi:'Tổng Pi để gửi', hi:'जमा करने के लिए कुल Pi', pt:'Pi total para depositar', tl:'Kabuuang Pi para i-deposit', fr:'Pi total à déposer' },
  lp_no_pi_price:   { ko:'Pi 시세 정보 없음', en:'No Pi price data', id:'Tidak ada data harga Pi', zh:'无 Pi 价格信息', ja:'Pi価格情報なし', es:'Sin datos de precio Pi', vi:'Không có dữ liệu giá Pi', hi:'Pi मूल्य डेटा नहीं', pt:'Sem dados de preço Pi', tl:'Walang datos sa presyo ng Pi', fr:'Pas de données de prix Pi' },
  lp_no_calc:       { ko:'두 토큰 모두 Pi 시세 정보가 없어 계산할 수 없습니다.', en:'Cannot calculate — no Pi price for either token.', id:'Tidak dapat menghitung — tidak ada harga Pi untuk kedua token.', zh:'两种代币均无Pi价格，无法计算。', ja:'両トークンともPi価格がなく計算できません。', es:'No se puede calcular — sin precio Pi para ningún token.', vi:'Không thể tính — không có giá Pi cho cả hai token.', hi:'गणना नहीं हो सकती — किसी भी टोकन के लिए Pi मूल्य नहीं।', pt:'Não é possível calcular — sem preço Pi para nenhum token.', tl:'Hindi makalkulahin — walang presyo ng Pi para sa alinmang token.', fr:'Calcul impossible — pas de prix Pi pour aucun token.' },
  lp_initial_note:  { ko:'초기 예치 비율이 곧 시작 가격이 됩니다. 아래는 현재 Pi 시세 기준 추천 비율입니다.', en:'The initial deposit ratio becomes the starting price. Below is the recommended ratio based on current Pi prices.', id:'Rasio deposit awal menjadi harga awal. Berikut adalah rasio yang disarankan berdasarkan harga Pi saat ini.', zh:'初始存款比例即为初始价格。以下是基于当前Pi价格的推荐比例。', ja:'初期預入比率が開始価格となります。現在Pi価格に基づく推奨比率です。', es:'La proporción inicial de depósito se convierte en el precio inicial. Abajo está la proporción recomendada según los precios actuales de Pi.', vi:'Tỷ lệ gửi ban đầu trở thành giá khởi điểm. Dưới đây là tỷ lệ khuyến nghị dựa trên giá Pi hiện tại.', hi:'प्रारंभिक जमा अनुपात प्रारंभिक मूल्य बन जाता है। नीचे वर्तमान Pi मूल्यों के आधार पर अनुशंसित अनुपात है।', pt:'A proporção inicial de depósito torna-se o preço inicial. Abaixo está a proporção recomendada com base nos preços atuais do Pi.', tl:'Ang panimulang ratio ng deposit ay nagiging panimulang presyo. Nasa ibaba ang inirerekomendang ratio batay sa kasalukuyang presyo ng Pi.', fr:"Le ratio de dépôt initial devient le prix de départ. Ci-dessous le ratio recommandé basé sur les prix actuels du Pi." },
  lp_new_pool_label:{ ko:'새 풀', en:'New Pool', id:'Pool Baru', zh:'新池', ja:'新しいプール', es:'Nuevo Pool', vi:'Pool mới', hi:'नया पूल', pt:'Novo Pool', tl:'Bagong Pool', fr:'Nouveau Pool' },
  lp_pool_label:    { ko:'풀', en:'Pool', id:'Pool', zh:'池', ja:'プール', es:'Pool', vi:'Pool', hi:'पूल', pt:'Pool', tl:'Pool', fr:'Pool' },
  lp_preview:       { ko:'예치 미리보기', en:'Preview', id:'Pratinjau Deposit', zh:'存款预览', ja:'預入プレビュー', es:'Vista previa', vi:'Xem trước gửi tiền', hi:'जमा पूर्वावलोकन', pt:'Visualização do depósito', tl:'Preview ng Deposit', fr:'Aperçu du dépôt' },
  lp_ratio_label:   { ko:'비율', en:'Ratio', id:'Rasio', zh:'比例', ja:'比率', es:'Ratio', vi:'Tỷ lệ', hi:'अनुपात', pt:'Proporção', tl:'Ratio', fr:'Ratio' },
  lp_token_ratio:   { ko:'수량 비율', en:'Token Ratio', id:'Rasio Token', zh:'数量比例', ja:'数量比率', es:'Ratio de token', vi:'Tỷ lệ token', hi:'टोकन अनुपात', pt:'Proporção de token', tl:'Token Ratio', fr:'Ratio de token' },
  lp_pool_ratio:    { ko:'비율', en:'Ratio', id:'Rasio', zh:'比例', ja:'比率', es:'Ratio', vi:'Tỷ lệ', hi:'अनुपात', pt:'Proporção', tl:'Ratio', fr:'Ratio' },
  lp_pool_fee:      { ko:'수수료', en:'Fee', id:'Biaya', zh:'手续费', ja:'手数料', es:'Comisión', vi:'Phí', hi:'शुल्क', pt:'Taxa', tl:'Bayad', fr:'Frais' },

  // ── Swap ──
  swap_title:       { ko:'스왑 시뮬레이터', en:'Swap Simulator',  id:'Simulator Swap',   zh:'兑换模拟器',    ja:'スワップシミュレーター', es:'Simulador de Swap',    vi:'Trình mô phỏng Swap',  hi:'Swap सिम्युलेटर',  pt:'Simulador de Swap',    tl:'Swap Simulator',         fr:'Simulateur de Swap' },
  swap_send:        { ko:'보내는 토큰', en:'Send',          id:'Token Dikirim',    zh:'发送代币',      ja:'送るトークン',         es:'Token a enviar',       vi:'Token gửi đi',         hi:'भेजने का टोकन',    pt:'Token a enviar',       tl:'Token na ipapadala',     fr:'Token à envoyer' },
  swap_receive:     { ko:'받는 토큰',  en:'Receive',        id:'Token Diterima',   zh:'接收代币',      ja:'受け取るトークン',     es:'Token a recibir',      vi:'Token nhận về',        hi:'प्राप्त टोकन',     pt:'Token a receber',      tl:'Token na matatanggap',   fr:'Token à recevoir' },
  swap_amount:      { ko:'수량',      en:'Amount',          id:'Jumlah',           zh:'数量',          ja:'数量',                es:'Cantidad',             vi:'Số lượng',             hi:'राशि',             pt:'Quantidade',           tl:'Halaga',                 fr:'Montant' },
  swap_dir:         { ko:'방향 전환', en:'Swap direction',  id:'Balik arah',       zh:'切换方向',      ja:'方向転換',            es:'Cambiar dirección',    vi:'Đổi hướng',            hi:'दिशा बदलें',       pt:'Inverter direção',     tl:'Baguhin ang direksyon',  fr:'Inverser la direction' },
  swap_breakdown:   { ko:'스왑 분석', en:'Swap Breakdown',  id:'Analisis Swap',    zh:'兑换分析',      ja:'スワップ分析',         es:'Análisis de swap',     vi:'Phân tích swap',       hi:'Swap विश्लेषण',    pt:'Análise de swap',      tl:'Swap Breakdown',         fr:'Analyse de swap' },
  swap_no_pool:     { ko:'해당 쌍의 풀이 없습니다', en:'No pool found', id:'Pool tidak ditemukan', zh:'该交易对无池', ja:'そのペアのプールがありません', es:'Sin pool para ese par', vi:'Không có pool cho cặp này', hi:'इस जोड़े के लिए कोई पूल नहीं', pt:'Sem pool para este par', tl:'Walang pool para sa pair na ito', fr:'Aucun pool pour cette paire' },
  swap_send_lbl:    { ko:'보내는 양', en:'Send',            id:'Jumlah dikirim',   zh:'发送量',        ja:'送る量',              es:'Envío',                vi:'Số gửi',               hi:'भेजी गई मात्रा',   pt:'Enviar',               tl:'Ipapadala',              fr:'Envoi' },
  swap_amm_fee:     { ko:'AMM 수수료', en:'AMM Fee',        id:'Biaya AMM',        zh:'AMM 手续费',    ja:'AMM手数料',           es:'Comisión AMM',         vi:'Phí AMM',              hi:'AMM शुल्क',        pt:'Taxa AMM',             tl:'AMM Fee',                fr:'Frais AMM' },
  swap_gas:         { ko:'가스비',   en:'Gas Fee',          id:'Biaya Gas',        zh:'Gas 费',        ja:'ガス代',              es:'Comisión Gas',         vi:'Phí gas',              hi:'गैस शुल्क',        pt:'Taxa de Gas',          tl:'Gas Fee',                fr:'Frais de Gas' },
  swap_impact:      { ko:'가격충격', en:'Price Impact',     id:'Dampak Harga',     zh:'价格影响',      ja:'価格インパクト',       es:'Impacto en precio',    vi:'Tác động giá',         hi:'मूल्य प्रभाव',     pt:'Impacto no preço',     tl:'Price Impact',           fr:'Impact sur le prix' },
  swap_net_in:      { ko:'실제 교환량', en:'Net Input',     id:'Input Bersih',     zh:'实际兑换量',    ja:'実際交換量',           es:'Entrada neta',         vi:'Lượng thực tế',        hi:'शुद्ध इनपुट',      pt:'Entrada líquida',      tl:'Net Input',              fr:'Entrée nette' },
  swap_recv_lbl:    { ko:'받는 양',  en:'Receive',          id:'Jumlah diterima',  zh:'接收量',        ja:'受け取り量',           es:'Recibir',              vi:'Số nhận',              hi:'प्राप्त मात्रा',   pt:'Receber',              tl:'Matatanggap',            fr:'Réception' },
  swap_rate:        { ko:'환율',     en:'Rate',             id:'Kurs',             zh:'汇率',          ja:'レート',              es:'Tasa',                 vi:'Tỷ giá',               hi:'दर',               pt:'Taxa',                 tl:'Rate',                   fr:'Taux' },
  swap_no_route:    { ko:'직접 풀 없음 (멀티홉 미지원)', en:'No direct pool (multi-hop not supported)', id:'Pool langsung tidak ada', zh:'无直接池（不支持多跳）', ja:'直接プールなし（マルチホップ非対応）', es:'Sin pool directo (multi-hop no soportado)', vi:'Không có pool trực tiếp (chưa hỗ trợ multi-hop)', hi:'कोई सीधा पूल नहीं (मल्टी-हॉप असमर्थित)', pt:'Sem pool direto (multi-hop não suportado)', tl:'Walang direktang pool (hindi supported ang multi-hop)', fr:"Pas de pool direct (multi-hop non supporté)" },
  swap_token_fail:  { ko:'토큰 목록 조회 실패', en:'Token list failed', id:'Gagal memuat token', zh:'代币列表加载失败', ja:'トークンリスト取得失敗', es:'Error al cargar tokens', vi:'Lỗi tải danh sách token', hi:'टोकन सूची विफल', pt:'Falha ao carregar tokens', tl:'Nabigo ang pag-load ng token list', fr:'Échec chargement des tokens' },
  lpsplit_title:    { ko:'LP 예치 준비', en:'LP Split Calc',  id:'Persiapan Deposit LP', zh:'LP 存款准备', ja:'LP預入準備',      es:'Preparación LP Split', vi:'Chuẩn bị gửi LP',   hi:'LP जमा की तैयारी', pt:'Preparação de depósito LP', tl:'Paghahanda ng LP Deposit', fr:'Préparation dépôt LP' },
  lpsplit_hint:     { ko:'보유 토큰의 일부를 교환해 LP 예치 비율을 맞출 때 사용하세요.', en:'Use this to split your holdings into the right ratio for LP deposit.', id:'Gunakan ini untuk membagi aset ke rasio yang tepat untuk deposit LP.', zh:'将持仓部分兑换以匹配LP存款比例。', ja:'保有トークンの一部を交換してLP預入比率を合わせましょう。', es:'Use esto para dividir sus activos en la proporción correcta para depositar en LP.', vi:'Dùng công cụ này để chia tài sản theo đúng tỷ lệ gửi LP.', hi:'LP जमा के लिए सही अनुपात में संपत्ति विभाजित करने के लिए इसका उपयोग करें।', pt:'Use isto para dividir seus ativos na proporção correta para depositar em LP.', tl:'Gamitin ito para hatiin ang iyong assets sa tamang ratio para sa LP deposit.', fr:'Utilisez ceci pour diviser vos avoirs dans le bon ratio pour déposer en LP.' },
  lpsplit_token:    { ko:'보유 토큰 / 수량', en:'Token / Amount', id:'Token / Jumlah', zh:'持有代币 / 数量', ja:'保有トークン / 数量', es:'Token / Cantidad', vi:'Token / Số lượng', hi:'टोकन / मात्रा', pt:'Token / Quantidade', tl:'Token / Halaga', fr:'Token / Montant' },
  lpsplit_target:   { ko:'교환할 상대 토큰', en:'Target Token',   id:'Token Tujuan',    zh:'兑换目标代币',  ja:'交換先トークン',      es:'Token destino',        vi:'Token mục tiêu',       hi:'लक्ष्य टोकन',      pt:'Token alvo',           tl:'Target Token',           fr:'Token cible' },
  lpsplit_pct:      { ko:'교환에 사용할 비율', en:'Exchange %',   id:'Rasio pertukaran', zh:'兑换使用比例', ja:'交換に使う比率',       es:'% a intercambiar',     vi:'Tỷ lệ dùng để đổi',   hi:'विनिमय के लिए %',  pt:'% para trocar',        tl:'Porsyento para i-exchange', fr:'% à échanger' },
  lpsplit_result:   { ko:'예치 준비 분석',   en:'Split Breakdown', id:'Analisis Pembagian', zh:'存款准备分析', ja:'預入準備分析',        es:'Análisis de split',    vi:'Phân tích chia tỷ lệ', hi:'विभाजन विश्लेषण',  pt:'Análise de divisão',   tl:'Split Breakdown',        fr:'Analyse de division' },
  lpsplit_total:    { ko:'전체 보유',        en:'Total',           id:'Total dimiliki',   zh:'总持仓',        ja:'総保有',              es:'Total',                vi:'Tổng sở hữu',          hi:'कुल',              pt:'Total',                tl:'Kabuuan',                fr:'Total' },
  lpsplit_portion:  { ko:'교환 사용',        en:'Swap portion',    id:'Bagian swap',      zh:'用于兑换',      ja:'交換使用分',          es:'Porción swap',         vi:'Phần để swap',         hi:'स्वैप हिस्सा',     pt:'Porção de swap',       tl:'Bahagi ng swap',         fr:"Portion d'échange" },
  lpsplit_ready:    { ko:'예치 준비 결과',   en:'Ready to Deposit',id:'Siap Deposit',     zh:'存款准备结果',  ja:'預入準備結果',         es:'Listo para depositar', vi:'Sẵn sàng gửi',         hi:'जमा के लिए तैयार', pt:'Pronto para depositar',tl:'Handa nang i-deposit',   fr:'Prêt à déposer' },
  lpsplit_remain:   { ko:'잔여',  en:'remaining', id:'tersisa', zh:'剩余', ja:'残り', es:'restante', vi:'còn lại', hi:'शेष', pt:'restante', tl:'natitira', fr:'restant' },
  lpsplit_received: { ko:'수령',  en:'received',  id:'diterima', zh:'已收到', ja:'受け取り', es:'recibido', vi:'đã nhận', hi:'प्राप्त', pt:'recebido', tl:'natanggap', fr:'reçu' },

  // ── Arbitrage ──
  arb_title:        { ko:'차익 탐색',      en:'Arbitrage Finder',   id:'Pencarian Arbitrase', zh:'套利查找',      ja:'アービトラージ探索',   es:'Buscador de Arbitraje',    vi:'Tìm kiếm Arbitrage',   hi:'आर्बिट्राज खोजक',  pt:'Buscador de Arbitragem',   tl:'Arbitrage Finder',        fr:"Recherche d'Arbitrage" },
  arb_settings:     { ko:'탐색 설정',      en:'Scan Settings',      id:'Pengaturan Pemindaian', zh:'探索设置',    ja:'探索設定',             es:'Ajustes de búsqueda',      vi:'Cài đặt tìm kiếm',     hi:'स्कैन सेटिंग',     pt:'Configurações de busca',   tl:'Mga Setting ng Scan',     fr:'Paramètres de recherche' },
  arb_input:        { ko:'투입금액',       en:'Input Amount',       id:'Jumlah Input',        zh:'投入金额',      ja:'投入金額',             es:'Monto de entrada',         vi:'Số tiền đầu vào',      hi:'इनपुट राशि',       pt:'Valor de entrada',         tl:'Halaga ng Input',         fr:"Montant d'entrée" },
  arb_target:       { ko:'기대 수익률',    en:'Target Return',      id:'Target Return',       zh:'预期收益率',    ja:'期待収益率',           es:'Retorno objetivo',         vi:'Lợi nhuận mục tiêu',   hi:'लक्ष्य रिटर्न',    pt:'Retorno alvo',             tl:'Target Return',           fr:'Retour cible' },
  arb_target_hint:  { ko:'이 수익률 이상인 경로만 표시', en:'Only show paths above this return', id:'Hanya tampilkan jalur di atas return ini', zh:'仅显示高于此收益率的路径', ja:'この収益率以上の経路のみ表示', es:'Solo mostrar rutas por encima de este retorno', vi:'Chỉ hiển thị đường đi vượt ngưỡng này', hi:'केवल इस रिटर्न से ऊपर के रास्ते दिखाएं', pt:'Mostrar apenas caminhos acima deste retorno', tl:'Ipakita lang ang mga path na nasa itaas ng return na ito', fr:'Afficher uniquement les chemins au-dessus de ce retour' },
  arb_min:          { ko:'최소 수익률',    en:'Min Return',         id:'Return Minimum',      zh:'最低收益率',    ja:'最低収益率',           es:'Retorno mínimo',           vi:'Lợi nhuận tối thiểu',  hi:'न्यूनतम रिटर्न',   pt:'Retorno mínimo',           tl:'Min Return',              fr:'Retour minimum' },
  arb_min_hint:     { ko:'이 미만은 실행 비추천으로 표시', en:'Below this is marked as not recommended', id:'Di bawah ini ditandai tidak direkomendasikan', zh:'低于此值标记为不推荐', ja:'これ未満は非推薦として表示', es:'Por debajo de esto se marca como no recomendado', vi:'Dưới mức này được đánh dấu không khuyến nghị', hi:'इससे कम को अनुशंसित नहीं के रूप में चिह्नित किया जाएगा', pt:'Abaixo disso é marcado como não recomendado', tl:'Ang nasa ibaba nito ay minarkahan bilang hindi inirerekomenda', fr:'En dessous, marqué comme non recommandé' },
  arb_liq:          { ko:'최소 유동성',    en:'Min Liquidity',      id:'Likuiditas Minimum',  zh:'最低流动性',    ja:'最低流動性',           es:'Liquidez mínima',          vi:'Thanh khoản tối thiểu', hi:'न्यूनतम तरलता',    pt:'Liquidez mínima',          tl:'Min Liquidity',           fr:'Liquidité minimale' },
  arb_liq_hint:     { ko:'풀 양쪽 중 작은 쪽 기준으로 필터', en:'Filter by smaller side of pool', id:'Filter berdasarkan sisi pool terkecil', zh:'按池中较小一方过滤', ja:'プールの小さい方を基準にフィルタ', es:'Filtrar por el lado menor del pool', vi:'Lọc theo cạnh nhỏ hơn của pool', hi:'पूल की छोटी साइड के आधार पर फ़िल्टर करें', pt:'Filtrar pelo lado menor do pool', tl:'I-filter batay sa mas maliit na panig ng pool', fr:'Filtrer selon le plus petit côté du pool' },
  arb_scan_btn:     { ko:'경로 탐색',      en:'Find Paths',         id:'Cari Jalur',          zh:'搜索路径',      ja:'経路探索',             es:'Buscar rutas',             vi:'Tìm đường đi',         hi:'रास्ते खोजें',     pt:'Buscar caminhos',          tl:'Hanapin ang mga Path',    fr:'Trouver des chemins' },
  arb_subscribed:   { ko:'구독 중 — 무제한 탐색', en:'Subscribed — Unlimited', id:'Berlangganan — Tanpa Batas', zh:'已订阅 — 无限探索', ja:'サブスク中 — 無制限', es:'Suscrito — Sin límite', vi:'Đã đăng ký — Không giới hạn', hi:'सदस्यता — असीमित', pt:'Assinado — Ilimitado', tl:'Nakasubscribe — Walang Limitasyon', fr:'Abonné — Illimité' },
  arb_remaining:    { ko:'오늘 남은 탐색 횟수', en:'Daily remaining', id:'Sisa hari ini', zh:'今日剩余次数', ja:'本日残り探索回数', es:'Restantes hoy', vi:'Còn lại hôm nay', hi:'आज शेष', pt:'Restantes hoje', tl:'Natitira ngayon', fr:"Restants aujourd'hui" },
  arb_resets:       { ko:'내일 초기화됩니다', en:'Resets tomorrow', id:'Reset besok', zh:'明日重置', ja:'明日リセットされます', es:'Se reinicia mañana', vi:'Đặt lại vào ngày mai', hi:'कल रीसेट होगा', pt:'Reinicia amanhã', tl:'Ire-reset bukas', fr:'Se réinitialise demain' },
  arb_over:         { ko:'오늘 탐색 횟수(100회)를 모두 사용했습니다. 내일 초기화됩니다.', en:'Daily limit (100) reached. Resets tomorrow.', id:'Batas harian (100) tercapai. Reset besok.', zh:'今日探索次数（100次）已用完，明日重置。', ja:'本日の探索回数（100回）を使い切りました。明日リセットされます。', es:'Límite diario (100) alcanzado. Se reinicia mañana.', vi:'Đã đạt giới hạn hàng ngày (100). Đặt lại vào ngày mai.', hi:'दैनिक सीमा (100) पहुंच गई। कल रीसेट होगा।', pt:'Limite diário (100) atingido. Reinicia amanhã.', tl:'Naabot na ang limitasyon (100) ngayon. Ire-reset bukas.', fr:'Limite journalière (100) atteinte. Réinitialisation demain.' },
  arb_scanning:     { ko:'풀 스캔 중...', en:'Scanning pools...', id:'Memindai pool...', zh:'扫描池中...', ja:'プールスキャン中...', es:'Escaneando pools...', vi:'Đang quét pool...', hi:'पूल स्कैन हो रहे हैं...', pt:'Varrendo pools...', tl:'Siniscan ang mga pool...', fr:'Analyse des pools...' },
  arb_loading_pools:{ ko:'전체 풀 로드 중... (페이지네이션)', en:'Loading all pools...', id:'Memuat semua pool...', zh:'加载全部池中...', ja:'全プール読込中...', es:'Cargando todos los pools...', vi:'Đang tải tất cả pool...', hi:'सभी पूल लोड हो रहे हैं...', pt:'Carregando todos os pools...', tl:'Nilo-load ang lahat ng pool...', fr:'Chargement de tous les pools...' },
  arb_no_liq:       { ko:'유동성 조건을 만족하는 풀이 없습니다.\n최소 유동성 값을 낮춰보세요.', en:'No pools meet the liquidity requirement.\nTry lowering the minimum.', id:'Tidak ada pool yang memenuhi syarat likuiditas.\nCoba turunkan minimumnya.', zh:'没有池满足流动性条件。\n请降低最低流动性值。', ja:'流動性条件を満たすプールがありません。\n最低流動性を下げてみてください。', es:'Ningún pool cumple el requisito de liquidez.\nIntente bajar el mínimo.', vi:'Không có pool nào đáp ứng yêu cầu thanh khoản.\nThử giảm mức tối thiểu.', hi:'कोई पूल तरलता आवश्यकता पूरी नहीं करता।\nन्यूनतम कम करके देखें।', pt:'Nenhum pool atende ao requisito de liquidez.\nTente diminuir o mínimo.', tl:'Walang pool na nakakatugon sa kinakailangan ng liquidity.\nSubukan bawasan ang minimum.', fr:'Aucun pool ne satisfait la liquidité minimale.\nEssayez de baisser le minimum.' },
  arb_total_pools:  { ko:'전체 풀', en:'Total pools', id:'Total pool', zh:'全部池', ja:'全プール', es:'Pools totales', vi:'Tổng số pool', hi:'कुल पूल', pt:'Total de pools', tl:'Kabuuang mga pool', fr:'Pools totaux' },
  arb_liq_pass:     { ko:'유동성 통과', en:'passed liquidity filter', id:'lolos filter likuiditas', zh:'通过流动性过滤', ja:'流動性フィルター通過', es:'pasó el filtro de liquidez', vi:'qua lọc thanh khoản', hi:'तरलता फ़िल्टर पास', pt:'passou filtro de liquidez', tl:'pumasa sa liquidity filter', fr:'a passé le filtre de liquidité' },
  arb_paths:        { ko:'경로', en:'paths', id:'jalur', zh:'路径', ja:'経路', es:'rutas', vi:'đường đi', hi:'रास्ते', pt:'caminhos', tl:'mga path', fr:'chemins' },
  arb_scanned:      { ko:'탐색', en:'scanned', id:'dipindai', zh:'已探索', ja:'探索', es:'escaneado', vi:'đã quét', hi:'स्कैन', pt:'varridos', tl:'na-scan', fr:'analysés' },
  arb_no_result:    { ko:'기대 수익률 이상인 경로 없음', en:'No paths above target return', id:'Tidak ada jalur di atas target return', zh:'无高于预期收益率的路径', ja:'期待収益率以上の経路なし', es:'Sin rutas sobre el retorno objetivo', vi:'Không có đường đi vượt lợi nhuận mục tiêu', hi:'लक्ष्य रिटर्न से ऊपर कोई रास्ता नहीं', pt:'Nenhum caminho acima do retorno alvo', tl:'Walang mga path na higit sa target return', fr:'Aucun chemin au-dessus du retour cible' },
  arb_found:        { ko:'수익 가능 경로', en:'profitable paths', id:'jalur menguntungkan', zh:'可盈利路径', ja:'収益可能経路', es:'rutas rentables', vi:'đường đi có lợi', hi:'लाभदायक रास्ते', pt:'caminhos lucrativos', tl:'mga profitable na path', fr:'chemins profitables' },
  arb_lower:        { ko:'기대 수익률을 낮춰보세요', en:'Try lowering the target return', id:'Coba turunkan target return', zh:'请降低预期收益率', ja:'期待収益率を下げてみてください', es:'Intente bajar el retorno objetivo', vi:'Thử giảm lợi nhuận mục tiêu', hi:'लक्ष्य रिटर्न कम करके देखें', pt:'Tente diminuir o retorno alvo', tl:'Subukang bawasan ang target return', fr:'Essayez de baisser le retour cible' },
  arb_none:         { ko:'수익 가능 경로 없음 (테스트넷 풀 유동성이 부족할 수 있습니다)', en:'No profitable paths (testnet liquidity may be low)', id:'Tidak ada jalur menguntungkan (likuiditas testnet mungkin rendah)', zh:'无可盈利路径（测试网流动性可能不足）', ja:'収益可能経路なし（テストネットの流動性が不足の可能性あり）', es:'Sin rutas rentables (liquidez de testnet puede ser baja)', vi:'Không có đường đi có lợi (thanh khoản testnet có thể thấp)', hi:'कोई लाभदायक रास्ता नहीं (टेस्टनेट तरलता कम हो सकती है)', pt:'Nenhum caminho lucrativo (liquidez do testnet pode ser baixa)', tl:'Walang profitable na path (maaaring mababa ang liquidity ng testnet)', fr:'Aucun chemin profitable (liquidité testnet peut être faible)' },
  arb_error:        { ko:'오류', en:'Error', id:'Kesalahan', zh:'错误', ja:'エラー', es:'Error', vi:'Lỗi', hi:'त्रुटि', pt:'Erro', tl:'Error', fr:'Erreur' },
  arb_amm_fee:      { ko:'AMM 수수료', en:'AMM Fee', id:'Biaya AMM', zh:'AMM 手续费', ja:'AMM手数料', es:'Comisión AMM', vi:'Phí AMM', hi:'AMM शुल्क', pt:'Taxa AMM', tl:'AMM Fee', fr:'Frais AMM' },
  arb_gas:          { ko:'가스비', en:'Gas Fee', id:'Biaya Gas', zh:'Gas 费', ja:'ガス代', es:'Comisión Gas', vi:'Phí gas', hi:'गैस शुल्क', pt:'Taxa de Gas', tl:'Gas Fee', fr:'Frais de Gas' },
  arb_impact:       { ko:'가격충격', en:'Price Impact', id:'Dampak Harga', zh:'价格影响', ja:'価格インパクト', es:'Impacto en precio', vi:'Tác động giá', hi:'मूल्य प्रभाव', pt:'Impacto no preço', tl:'Price Impact', fr:'Impact sur le prix' },
  arb_net:          { ko:'순 수익률', en:'Net Return', id:'Return Bersih', zh:'净收益率', ja:'純収益率', es:'Retorno neto', vi:'Lợi nhuận ròng', hi:'शुद्ध रिटर्न', pt:'Retorno líquido', tl:'Net Return', fr:'Retour net' },
  arb_output:       { ko:'예상 수령량', en:'Expected Output', id:'Output Diharapkan', zh:'预期收到量', ja:'予想受取量', es:'Salida esperada', vi:'Số lượng dự kiến nhận', hi:'अनुमानित आउटपुट', pt:'Saída esperada', tl:'Expected Output', fr:'Sortie attendue' },
  arb_caution:      { ko:'⚠️ 실행 비추천 (최소 수익률 미달)', en:'⚠️ Not recommended (below min return)', id:'⚠️ Tidak disarankan (di bawah return minimum)', zh:'⚠️ 不推荐执行（低于最低收益率）', ja:'⚠️ 実行非推薦（最低収益率未達）', es:'⚠️ No recomendado (por debajo del retorno mínimo)', vi:'⚠️ Không khuyến nghị (dưới mức lợi nhuận tối thiểu)', hi:'⚠️ अनुशंसित नहीं (न्यूनतम रिटर्न से कम)', pt:'⚠️ Não recomendado (abaixo do retorno mínimo)', tl:'⚠️ Hindi inirerekomenda (sa ibaba ng minimum return)', fr:'⚠️ Non recommandé (sous le retour minimum)' },

  // ── Wallet ──
  wallet_title:     { ko:'지갑 현황',   en:'Wallet Overview',    id:'Ringkasan Dompet',  zh:'钱包状况',     ja:'ウォレット概況',      es:'Resumen de Cartera',     vi:'Tổng quan ví',       hi:'वॉलेट अवलोकन',   pt:'Visão geral da carteira', tl:'Pangkalahatang-tanaw ng Wallet', fr:'Aperçu du Portefeuille' },
  wallet_refresh:   { ko:'새로고침',    en:'Refresh',            id:'Segarkan',          zh:'刷新',         ja:'更新',                es:'Actualizar',             vi:'Làm mới',            hi:'रीफ्रेश',         pt:'Atualizar',               tl:'I-refresh',               fr:'Actualiser' },
  wallet_loading:   { ko:'잔액 조회 중...', en:'Loading...', id:'Memuat...', zh:'查询余额中...', ja:'残高照会中...', es:'Cargando...', vi:'Đang tải...', hi:'लोड हो रहा है...', pt:'Carregando...', tl:'Nilo-load...', fr:'Chargement...' },
  wallet_no_key:    { ko:'정보 탭에서 공개주소를 등록해주세요.', en:'Register your public key in the Info tab.', id:'Daftarkan kunci publik Anda di tab Info.', zh:'请在信息选项卡中注册公开地址。', ja:'情報タブで公開アドレスを登録してください。', es:'Registre su clave pública en la pestaña Info.', vi:'Hãy đăng ký địa chỉ công khai ở tab Thông tin.', hi:'Info टैब में अपनी सार्वजनिक कुंजी रजिस्टर करें।', pt:'Registre sua chave pública na aba Info.', tl:'I-register ang iyong public key sa Info tab.', fr:"Enregistrez votre clé publique dans l'onglet Info." },
  wallet_loading2:  { ko:'지갑 데이터 로드 중...', en:'Loading wallet data...', id:'Memuat data dompet...', zh:'加载钱包数据中...', ja:'ウォレットデータ読込中...', es:'Cargando datos de la cartera...', vi:'Đang tải dữ liệu ví...', hi:'वॉलेट डेटा लोड हो रहा है...', pt:'Carregando dados da carteira...', tl:'Nilo-load ang datos ng wallet...', fr:'Chargement des données du portefeuille...' },
  wallet_pi:        { ko:'테스트 Pi', en:'Test Pi Balance', id:'Saldo Pi Uji', zh:'测试 Pi', ja:'テスト Pi', es:'Pi de Prueba', vi:'Pi thử nghiệm', hi:'टेस्ट Pi', pt:'Pi de Teste', tl:'Test Pi', fr:'Pi de Test' },
  wallet_total:     { ko:'총 보유', en:'Total', id:'Total', zh:'总持有', ja:'総保有', es:'Total', vi:'Tổng', hi:'कुल', pt:'Total', tl:'Kabuuan', fr:'Total' },
  wallet_avail:     { ko:'사용 가능', en:'Available', id:'Tersedia', zh:'可用', ja:'利用可能', es:'Disponible', vi:'Có thể dùng', hi:'उपलब्ध', pt:'Disponível', tl:'Available', fr:'Disponible' },
  wallet_reserve:   { ko:'최소 예비금', en:'Min Reserve', id:'Cadangan Minimum', zh:'最低准备金', ja:'最低準備金', es:'Reserva mínima', vi:'Dự phòng tối thiểu', hi:'न्यूनतम रिज़र्व', pt:'Reserva mínima', tl:'Min Reserve', fr:'Réserve minimale' },
  wallet_reserve_note:{ ko:'계정 + 트러스트라인 × 0.5', en:'account + trustlines × 0.5', id:'akun + trustline × 0.5', zh:'账户 + 信托线 × 0.5', ja:'アカウント + トラストライン × 0.5', es:'cuenta + trustlines × 0.5', vi:'tài khoản + trustlines × 0.5', hi:'खाता + ट्रस्टलाइन × 0.5', pt:'conta + trustlines × 0.5', tl:'account + trustlines × 0.5', fr:'compte + trustlines × 0.5' },
  wallet_tokens:    { ko:'보유 토큰', en:'Token Balances', id:'Saldo Token', zh:'持有代币', ja:'保有トークン', es:'Saldos de tokens', vi:'Số dư token', hi:'टोकन बैलेंस', pt:'Saldos de tokens', tl:'Mga Token Balance', fr:'Soldes de tokens' },
  wallet_lp:        { ko:'LP 예치 현황', en:'LP Positions', id:'Posisi LP', zh:'LP 质押状况', ja:'LP預入状況', es:'Posiciones LP', vi:'Vị thế LP', hi:'LP पोजीशन', pt:'Posições LP', tl:'Mga LP Position', fr:'Positions LP' },
  wallet_no_lp:     { ko:'예치된 LP 없음', en:'No LP positions', id:'Tidak ada posisi LP', zh:'无质押 LP', ja:'預入済みLPなし', es:'Sin posiciones LP', vi:'Không có vị thế LP', hi:'कोई LP पोजीशन नहीं', pt:'Sem posições LP', tl:'Walang LP position', fr:'Aucune position LP' },
  wallet_share:     { ko:'풀 점유율', en:'Pool share', id:'Bagian pool', zh:'池占比', ja:'プールシェア', es:'Participación pool', vi:'Phần trong pool', hi:'पूल हिस्सा', pt:'Participação no pool', tl:'Pool share', fr:'Part dans le pool' },
  wallet_stake:     { ko:'지분', en:'shares', id:'bagian', zh:'份额', ja:'シェア', es:'partes', vi:'phần', hi:'शेयर', pt:'cotas', tl:'shares', fr:'parts' },
  wallet_trustlines:{ ko:'연결된 토큰', en:'Trustlines', id:'Trustline', zh:'已连接代币', ja:'トラストライン', es:'Trustlines', vi:'Trustlines', hi:'ट्रस्टलाइन', pt:'Trustlines', tl:'Mga Trustline', fr:'Trustlines' },
  wallet_no_balance:{ ko:'잔액 없음', en:'No balance', id:'Tidak ada saldo', zh:'无余额', ja:'残高なし', es:'Sin saldo', vi:'Không có số dư', hi:'कोई बैलेंस नहीं', pt:'Sem saldo', tl:'Walang balance', fr:'Pas de solde' },
  wallet_zero_tl:   { ko:'연결만 된 토큰 (잔액 없음)', en:'Trustlines with zero balance', id:'Trustline saldo nol', zh:'已连接但无余额代币', ja:'残高ゼロのトラストライン', es:'Trustlines con saldo cero', vi:'Trustlines với số dư bằng 0', hi:'शून्य बैलेंस वाले ट्रस्टलाइन', pt:'Trustlines com saldo zero', tl:'Mga trustline na walang balance', fr:'Trustlines avec solde zéro' },
  wallet_updated:   { ko:'조회 시각', en:'Updated at', id:'Diperbarui pukul', zh:'查询时刻', ja:'照会時刻', es:'Actualizado a las', vi:'Cập nhật lúc', hi:'अपडेट किया गया', pt:'Atualizado em', tl:'Na-update noong', fr:'Mis à jour à' },
  wallet_fail:      { ko:'조회 실패', en:'Load failed', id:'Gagal memuat', zh:'查询失败', ja:'照会失敗', es:'Error de carga', vi:'Lỗi tải', hi:'लोड विफल', pt:'Falha ao carregar', tl:'Nabigo ang pag-load', fr:'Échec du chargement' },
  wallet_check_key: { ko:'정보 탭에서 공개주소를 다시 확인해주세요.', en:'Please check your public key in the Info tab.', id:'Periksa kembali kunci publik Anda di tab Info.', zh:'请在信息选项卡中重新确认公开地址。', ja:'情報タブで公開アドレスを再確認してください。', es:'Compruebe su clave pública en la pestaña Info.', vi:'Hãy kiểm tra lại địa chỉ công khai ở tab Thông tin.', hi:'Info टैब में अपनी सार्वजनिक कुंजी जांचें।', pt:'Verifique sua chave pública na aba Info.', tl:'Suriin ang inyong public key sa Info tab.', fr:"Vérifiez votre clé publique dans l'onglet Info." },

  // ── Info / Subscription ──
  info_title:       { ko:'정보',       en:'Info',                  id:'Info',               zh:'信息',          ja:'情報',                es:'Info',                   vi:'Thông tin',            hi:'जानकारी',         pt:'Info',                   tl:'Info',                    fr:'Info' },
  info_about:       { ko:'앱 소개',    en:'About',                 id:'Tentang Aplikasi',   zh:'应用介绍',      ja:'アプリ紹介',           es:'Acerca de',              vi:'Giới thiệu ứng dụng',  hi:'ऐप के बारे में',  pt:'Sobre o App',            tl:'Tungkol sa App',          fr:'À propos' },
  info_notice:      { ko:'시뮬레이션 전용', en:'Simulation Only',  id:'Hanya Simulasi',     zh:'仅供模拟',      ja:'シミュレーション専用', es:'Solo Simulación',        vi:'Chỉ để mô phỏng',      hi:'केवल सिमुलेशन',   pt:'Somente Simulação',      tl:'Para sa Simulation Lamang', fr:'Simulation Uniquement' },
  info_notice_desc: { ko:'이 앱은 분석·시뮬레이션 도구입니다. 실제 거래는 Pi Browser의 PiDEX에서 직접 진행해주세요.', en:'This app is for analysis only. Execute trades on PiDEX in Pi Browser.', id:'Aplikasi ini hanya untuk analisis. Lakukan perdagangan nyata di PiDEX pada Pi Browser.', zh:'本应用仅为分析/模拟工具，请在Pi Browser的PiDEX中直接进行实际交易。', ja:'このアプリは分析・シミュレーションツールです。実際の取引はPi BrowserのPiDEXで行ってください。', es:'Esta app es solo para análisis. Ejecute las operaciones reales en PiDEX en Pi Browser.', vi:'Ứng dụng này chỉ để phân tích. Hãy thực hiện giao dịch thực tế trên PiDEX trong Pi Browser.', hi:'यह ऐप केवल विश्लेषण के लिए है। वास्तविक लेनदेन Pi Browser के PiDEX पर करें।', pt:'Este app é apenas para análise. Execute as negociações reais no PiDEX no Pi Browser.', tl:'Ang app na ito ay para sa pagsusuri lamang. Isagawa ang mga aktwal na trade sa PiDEX sa Pi Browser.', fr:"Cette application est réservée à l'analyse. Effectuez les transactions réelles sur PiDEX dans Pi Browser." },
  info_pubkey:      { ko:'지갑 공개주소 등록', en:'Register Wallet Address', id:'Daftarkan Alamat Dompet', zh:'注册钱包公开地址', ja:'ウォレット公開アドレス登録', es:'Registrar dirección de cartera', vi:'Đăng ký địa chỉ ví công khai', hi:'वॉलेट सार्वजनिक पता रजिस्टर करें', pt:'Registrar endereço público da carteira', tl:'I-register ang Wallet Address', fr:"Enregistrer l'adresse publique" },
  info_pubkey_desc: { ko:'Pi 지갑의 공개주소(G로 시작, 56자리)를 등록하면 지갑 탭이 활성화됩니다.\n총 보유 Pi, 토큰 잔액, LP 예치 현황 등을 확인할 수 있습니다. 공개주소는 읽기 전용으로 안전합니다.', en:'Register your public key (G..., 56 chars) to activate the Wallet tab and view Pi balance, tokens, and LP positions. Public key is read-only and safe.', id:'Daftarkan kunci publik Pi Anda (G..., 56 karakter) untuk mengaktifkan tab Dompet dan melihat saldo Pi, token, dan posisi LP. Kunci publik hanya untuk baca dan aman.', zh:'注册Pi钱包公开地址（以G开头，56位）可激活钱包选项卡，查看Pi余额、代币余额和LP质押状况。公开地址仅读取，安全可靠。', ja:'Pi ウォレットの公開アドレス（G始まり、56文字）を登録するとウォレットタブが有効になります。総保有Pi・トークン残高・LP預入状況等を確認できます。公開アドレスは読み取り専用で安全です。', es:'Registre su clave pública (G..., 56 chars) para activar la pestaña Cartera y ver saldo Pi, tokens y posiciones LP. La clave pública es de solo lectura y segura.', vi:'Đăng ký khóa công khai Pi (G..., 56 ký tự) để kích hoạt tab Ví và xem số dư Pi, token và vị thế LP. Khóa công khai chỉ đọc và an toàn.', hi:'Pi वॉलेट का सार्वजनिक पता (G..., 56 अक्षर) रजिस्टर करें। वॉलेट टैब सक्रिय होगा। Pi बैलेंस, टोकन और LP पोजीशन देखें। सुरक्षित।', pt:'Registre sua chave pública Pi (G..., 56 chars) para ativar a aba Carteira e ver saldo Pi, tokens e posições LP. Chave pública é somente leitura e segura.', tl:'I-register ang inyong public key ng Pi (G..., 56 character) para ma-activate ang Wallet tab at makita ang Pi balance, tokens at LP positions. Ligtas ang public key.', fr:"Enregistrez votre clé publique Pi (G..., 56 chars) pour activer l'onglet Portefeuille et voir votre solde Pi, tokens et positions LP. La clé publique est en lecture seule et sécurisée." },
  info_registered:  { ko:'등록됨', en:'Active', id:'Terdaftar', zh:'已注册', ja:'登録済み', es:'Activo', vi:'Đã đăng ký', hi:'पंजीकृत', pt:'Ativo', tl:'Nairehistro', fr:'Enregistré' },
  info_remove_key:  { ko:'주소 삭제', en:'Remove', id:'Hapus Alamat', zh:'删除地址', ja:'アドレス削除', es:'Eliminar', vi:'Xóa địa chỉ', hi:'हटाएं', pt:'Remover', tl:'I-remove', fr:'Supprimer' },
  info_save_key:    { ko:'등록', en:'Add', id:'Daftarkan', zh:'注册', ja:'登録', es:'Añadir', vi:'Đăng ký', hi:'जोड़ें', pt:'Adicionar', tl:'I-save', fr:'Ajouter' },
  info_key_ph:      { ko:'GXXXX... (56자리 공개주소)', en:'GXXXX... (56-char public key)', id:'GXXXX... (56 karakter kunci publik)', zh:'GXXXX... (56位公开地址)', ja:'GXXXX...（56文字の公開アドレス）', es:'GXXXX... (clave pública de 56 chars)', vi:'GXXXX... (56 ký tự, địa chỉ công khai)', hi:'GXXXX... (56 अक्षर की सार्वजनिक कुंजी)', pt:'GXXXX... (chave pública de 56 chars)', tl:'GXXXX... (56-character na public key)', fr:'GXXXX... (clé publique 56 caractères)' },
  info_contact:     { ko:'문의 및 피드백', en:'Contact & Feedback', id:'Kontak & Masukan', zh:'联系及反馈', ja:'お問い合わせとフィードバック', es:'Contacto y Comentarios', vi:'Liên hệ và phản hồi', hi:'संपर्क और फीडबैक', pt:'Contato e Feedback', tl:'Makipag-ugnayan at Feedback', fr:'Contact et Retours' },
  info_contact_desc:{ ko:'사용 중 문의사항이나 피드백은 유튜브 채널 댓글로 남겨주세요.', en:'Leave questions or feedback in the YouTube channel comments.', id:'Tinggalkan pertanyaan atau masukan di kolom komentar YouTube.', zh:'如有使用问题或反馈，请在YouTube频道评论区留言。', ja:'ご不明な点やフィードバックはYouTubeチャンネルのコメント欄にお寄せください。', es:'Deje preguntas o comentarios en los comentarios del canal de YouTube.', vi:'Hãy để lại câu hỏi hoặc phản hồi trong phần bình luận kênh YouTube.', hi:'प्रश्न या फीडबैक YouTube चैनल के कमेंट में छोड़ें।', pt:'Deixe perguntas ou feedback nos comentários do canal do YouTube.', tl:'Mag-iwan ng mga tanong o feedback sa mga komento ng YouTube channel.', fr:'Laissez vos questions ou commentaires dans les commentaires de la chaîne YouTube.' },
  info_copy:        { ko:'복사', en:'Copy', id:'Salin', zh:'复制', ja:'コピー', es:'Copiar', vi:'Sao chép', hi:'कॉपी करें', pt:'Copiar', tl:'Kopyahin', fr:'Copier' },
  info_copied:      { ko:'복사됨', en:'Copied!', id:'Tersalin!', zh:'已复制！', ja:'コピーしました！', es:'¡Copiado!', vi:'Đã sao chép!', hi:'कॉपी हो गया!', pt:'Copiado!', tl:'Nakopya na!', fr:'Copié !' },
  info_copy_note:   { ko:'위 주소를 복사 후 유튜브에서 검색해주세요.', en:'Copy the URL and search in YouTube.', id:'Salin URL dan cari di YouTube.', zh:'复制上方地址后在YouTube搜索。', ja:'上記URLをコピーしてYouTubeで検索してください。', es:'Copie la URL y búsquela en YouTube.', vi:'Sao chép URL và tìm kiếm trên YouTube.', hi:'URL कॉपी करें और YouTube पर खोजें।', pt:'Copie a URL e pesquise no YouTube.', tl:'Kopyahin ang URL at hanapin sa YouTube.', fr:"Copiez l'URL et recherchez sur YouTube." },
  info_key_removed: { ko:'공개주소가 삭제되었습니다.', en:'Public key removed.', id:'Kunci publik dihapus.', zh:'公开地址已删除。', ja:'公開アドレスが削除されました。', es:'Clave pública eliminada.', vi:'Đã xóa địa chỉ công khai.', hi:'सार्वजनिक कुंजी हटाई गई।', pt:'Chave pública removida.', tl:'Naalis na ang public key.', fr:'Clé publique supprimée.' },
  info_key_invalid: { ko:'G로 시작하는 56자리 공개주소를 입력해주세요.', en:'Please enter a valid 56-char public key starting with G.', id:'Masukkan kunci publik 56 karakter yang dimulai dengan G.', zh:'请输入以G开头的56位公开地址。', ja:'Gで始まる56文字の公開アドレスを入力してください。', es:'Ingrese una clave pública válida de 56 chars comenzando con G.', vi:'Vui lòng nhập địa chỉ công khai 56 ký tự bắt đầu bằng G.', hi:'G से शुरू होने वाली 56 अक्षर की सार्वजनिक कुंजी दर्ज करें।', pt:'Insira uma chave pública válida de 56 chars começando com G.', tl:'Maglagay ng valid na 56-character na public key na nagsisimula sa G.', fr:'Entrez une clé publique valide de 56 chars commençant par G.' },
  info_key_saved:   { ko:'등록 완료! 지갑 탭이 활성화됩니다.', en:'Saved! Wallet tab is now active.', id:'Tersimpan! Tab Dompet sekarang aktif.', zh:'注册成功！钱包选项卡已激活。', ja:'登録完了！ウォレットタブが有効になりました。', es:'¡Guardado! La pestaña Cartera ya está activa.', vi:'Đã lưu! Tab Ví hiện đã hoạt động.', hi:'सहेज लिया! वॉलेट टैब अब सक्रिय है।', pt:'Salvo! A aba Carteira agora está ativa.', tl:'Na-save na! Aktibo na ang Wallet tab.', fr:"Enregistré ! L'onglet Portefeuille est maintenant actif." },
};

function _detectLang() {
  const supported = ['ko','en','id','zh','ja','es','vi','hi','pt','tl','fr'];
  const nav = (navigator.languages?.[0] || navigator.language || 'en').toLowerCase();
  const primary = nav.split('-')[0];
  if (primary === 'fil') return 'tl';
  return supported.includes(primary) ? primary : 'en';
}
let _lang = localStorage.getItem('pidex_lang') || _detectLang();

export function getLang() { return _lang; }

export function setLang(lang) {
  _lang = lang;
  localStorage.setItem('pidex_lang', lang);
}

export function t(key) {
  const s = STRINGS[key];
  if (!s) return key;
  return s[_lang] ?? s.ko;
}
